SELECT E1.ID, IFNULL(C.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E1
LEFT JOIN 
    (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
     FROM ECOLI_DATA
     GROUP BY PARENT_ID
    ) AS C
ON E1.ID = C.PARENT_ID
ORDER BY E1.ID ASC;