SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT) * p.PRICE as TOTAL_SALES
FROM FOOD_PRODUCT p
    INNER JOIN FOOD_ORDER o on p.PRODUCT_ID = o.PRODUCT_ID
WHERE 1=1
    AND date_format(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC